# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 29 May 2011 01:13:22 +0000
*               @ALL          0
*               @user         8
