<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Tue, 28 Jun 2011 23:07:42 -0300
 */

$conf['title'] = 'LikaWiki';
$conf['lang'] = 'pt-br';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['iexssprotect'] = 0;
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['subscribers'] = 1;
$conf['fetchsize'] = 40960000;
$conf['plugin']['countdown']['business_days'] = 1;
$conf['plugin']['countdown']['time_message'] = 1;
$conf['tpl']['vector']['vector_mediamanager_embedded'] = 1;

// end auto-generated content
